name:                avdou-hs
version:             0.1.0.0
github:              githubuser/example-site
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2025 Author name here

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/example-site#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- yaml
- aeson
- filepath
- Glob
- pandoc >= 3.1.5.2
- mustache
- warp
- wai-app-static	
- megaparsec
- fsnotify
- time
- pandoc-types
- text
- lens
- bytestring

ghc-options:
- -O2
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src
